swiftmailer:
    transport: smtp
    auth_mode: login
    host: '%env(MAILER_HOST)%'
    port: 587
    username: '%env(MAILER_USERNAME)%'
    password: '%env(MAILER_PASSWORD)%'
    spool: { type: 'memory' }
